language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then pip install cryptography; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pip install cryptography; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install cryptography; fi
  - pip install pytest
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install coverage coveralls; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then ./generate.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then ./generate.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then ./generate.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coverage run --source pysyncobj -m py.test -v -l test_syncobj.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then py.test -v -l test_syncobj3.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then py.test -v -l test_syncobj3.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then py.test -v -l test_syncobj.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then py.test -v -l test_syncobj3.py; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi
