language: python
os:
  - linux
  - osx
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]
    then
      brew update || brew update # try again if it fails
      brew upgrade
      brew reinstall pyenv
      eval "$(pyenv init -)"

      if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
      then
        env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install --skip-existing 2.7.9
        pyenv global 2.7.9
        pyenv shell 2.7.9
      fi

      pip install -U pip setuptools wheel virtualenv
    fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 && $TRAVIS_OS_NAME == "linux" ]]; then pip install cryptography; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 && $TRAVIS_OS_NAME == "linux" ]]; then pip install cryptography; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install cryptography; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 || $TRAVIS_OS_NAME == "linux" ]]; then pip install pytest; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install coverage coveralls; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 && $TRAVIS_OS_NAME == "linux" ]]; then ./generate.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 && $TRAVIS_OS_NAME == "linux" ]]; then ./generate.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' && $TRAVIS_OS_NAME == "linux" ]]; then ./generate.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coverage run --source pysyncobj -m py.test -v -l test_syncobj.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 && $TRAVIS_OS_NAME == "linux" ]]; then py.test -v -l test_syncobj3.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 && $TRAVIS_OS_NAME == "linux" ]]; then py.test -v -l test_syncobj3.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' && $TRAVIS_OS_NAME == "linux" ]]; then py.test -v -l test_syncobj.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' && $TRAVIS_OS_NAME == "linux" ]]; then py.test -v -l test_syncobj3.py; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 && $TRAVIS_OS_NAME == "linux" ]]; then coveralls; fi
