language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - pip install pytest
  - if [[ ! $TRAVIS_PYTHON_VERSION =~ ^pypy ]]; then pip install cryptography coverage coveralls; fi
script:
  - if [[ ! $TRAVIS_PYTHON_VERSION =~ ^pypy ]]; then coverage run --source pysyncobj -m py.test -v -l test_syncobj.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION =~ ^pypy ]]; then py.test -v -l test_syncobj.py; fi
after_success:
  - if [[ ! $TRAVIS_PYTHON_VERSION =~ ^pypy ]]; then coveralls -v; fi
