language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install cryptography; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then ./gen_py3.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then ./gen_py3.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then ./gen_py3.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then python2.7 syncobj_ut.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then python3.4 syncobj3_ut.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then python3.5 syncobj3_ut.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pypy syncobj_ut.py nocrypto; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then pypy3 syncobj_ut.py; fi
